const GIT_KEYWORDS = ['Setup — Fetch', 'Write & Run Unit Tests', 'Create PR', 'Commit & Push'];

function isSystemStep(step) {
  return step.isGitStep || GIT_KEYWORDS.some(k => step.title.includes(k));
}

function getUserSteps(steps) {
  return steps.filter(s => !isSystemStep(s));
}

async function generatePRDescriptionWithAI(ticket, steps) {
  const vscode = require('vscode');
  const userSteps = getUserSteps(steps);
  const stepsSummary = userSteps.map((s, i) => `${i + 1}. [${s.checked ? 'DONE' : 'PENDING'}] ${s.title}`).join('\n');

  let models = [];
  try {
    models = await vscode.lm.selectChatModels({ family: 'gpt-4o' });
    if (!models?.length) models = await vscode.lm.selectChatModels();
  } catch (e) {}

  if (!models?.length) return generatePRPlain(ticket, userSteps);

  try {
    const model = models[0];
    const prompt = `You are a senior developer writing a pull request description.

Ticket: #${ticket.id} — ${ticket.title}
Type: ${ticket.type}

Tasks completed:
${stepsSummary}

Write a concise professional PR description with:
1. Brief summary (2-3 sentences)
2. Bullet list of what was implemented (completed items only)
3. Testing checklist

Important: Do NOT mention time. Do NOT include git/branch/commit steps.`;

    const messages = [vscode.LanguageModelChatMessage.User(prompt)];
    const cts = new vscode.CancellationTokenSource();
    let result = '';
    const response = await model.sendRequest(messages, {}, cts.token);
    for await (const chunk of response.text) result += chunk;
    return result.trim();
  } catch (e) { return generatePRPlain(ticket, userSteps); }
}

function generatePRPlain(ticket, userSteps) {
  const done = userSteps.filter(s => s.checked);
  const pending = userSteps.filter(s => !s.checked);
  return `## ${ticket.title}\n\n**Ticket:** #${ticket.id} · ${ticket.type}\n\n## What was done\n${done.map(s => `- ✅ ${s.title}`).join('\n') || '- No steps completed yet'}${pending.length ? `\n\n## Remaining\n${pending.map(s => `- ⬜ ${s.title}`).join('\n')}` : ''}\n\n## Checklist\n- [ ] Code reviewed\n- [ ] Tests passing\n- [ ] No console errors\n- [ ] Acceptance criteria verified`;
}

function generateMarkdownExport(ticket, steps) {
  const userSteps = getUserSteps(steps);
  const done = userSteps.filter(s => s.checked).length;
  const progress = userSteps.length ? Math.round((done / userSteps.length) * 100) : 0;

  return `# Flowzy Runbook — #${ticket.id}: ${ticket.title}\n\n**Generated:** ${new Date().toLocaleString()}\n**Type:** ${ticket.type} · **State:** ${ticket.state}${ticket.points ? ` · **Points:** ${ticket.points}` : ''}\n**Progress:** ${done}/${userSteps.length} steps (${progress}%)\n\n---\n\n## Steps\n\n${userSteps.map((s, i) => `### ${i + 1}. ${s.checked ? '✅' : '⬜'} ${s.title}\n- **Status:** ${s.checked ? 'Done' : 'Pending'}\n`).join('\n')}\n---\n\n*Generated by Flowzy for VS Code*`;
}

module.exports = { generatePRDescriptionWithAI, generateMarkdownExport, getUserSteps };
